name: Build binaries

on:

  push:
    branches:
        - master
  pull_request:
    paths:
    - '.github/workflows/*.yml'
    - './scripts/*.sh'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout builder
        uses: actions/checkout@v1

      - name: Install arm toolchain
        run: ./scripts/install_arm.sh

      - name: Checkout st7789_mpy/micropython
        run: ./scripts/init.sh

      - name: Create artifacts directory
        run: mkdir ./artifacts

      - name: Compile for raspberry pico W
        if: always()
        run: ./scripts/rp2/pico_w.sh


      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "Release date ${{ steps.date.outputs.date }}"
          files: ./artifacts/*
